{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "low"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2023-36632",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "** DISPUTED ** The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2023-36632",
				"url": "https://www.suse.com/security/cve/CVE-2023-36632"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1212717 for CVE-2023-36632",
				"url": "https://bugzilla.suse.com/1212717"
			}
		],
		"title": "SUSE CVE CVE-2023-36632",
		"tracking": {
			"current_release_date": "2025-01-10T01:13:13Z",
			"generator": {
				"date": "2023-06-27T01:25:06Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2023-36632",
			"initial_release_date": "2023-06-27T01:25:06Z",
			"revision_history": [
				{
					"date": "2023-06-27T01:25:06Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2025-01-01T02:01:50Z",
					"number": "3",
					"summary": "Current version"
				},
				{
					"date": "2025-01-10T01:13:13Z",
					"number": "4",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "4"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 7",
								"product": {
									"name": "SUSE Enterprise Storage 7",
									"product_id": "SUSE Enterprise Storage 7",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:7"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python",
								"product": {
									"name": "python",
									"product_id": "python",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3",
								"product": {
									"name": "python3",
									"product_id": "python3",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python as component of SUSE Enterprise Storage 7",
					"product_id": "SUSE Enterprise Storage 7:python"
				},
				"product_reference": "python",
				"relates_to_product_reference": "SUSE Enterprise Storage 7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3 as component of SUSE Enterprise Storage 7",
					"product_id": "SUSE Enterprise Storage 7:python3"
				},
				"product_reference": "python3",
				"relates_to_product_reference": "SUSE Enterprise Storage 7"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-36632",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-36632"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "** DISPUTED ** The legacy email.utils.parseaddr function in Python through 3.11.4 allows attackers to trigger \"RecursionError: maximum recursion depth exceeded while calling a Python object\" via a crafted argument. This argument is plausibly an untrusted value from an application's input data that was supposed to contain a name and an e-mail address. NOTE: email.utils.parseaddr is categorized as a Legacy API in the documentation of the Python email package. Applications should instead use the email.parser.BytesParser or email.parser.Parser class. NOTE: the vendor's perspective is that this is neither a vulnerability nor a bug. The email package is intended to have size limits and to throw an exception when limits are exceeded; they were exceeded by the example demonstration code.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"known_affected": [
					"SUSE Enterprise Storage 7:python",
					"SUSE Enterprise Storage 7:python3"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-36632",
					"url": "https://www.suse.com/security/cve/CVE-2023-36632"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1212717 for CVE-2023-36632",
					"url": "https://bugzilla.suse.com/1212717"
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2023-06-25T20:00:06Z",
					"details": "low"
				}
			],
			"title": "CVE-2023-36632"
		}
	]
}
