{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2019-19588",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2019-19588",
				"url": "https://www.suse.com/security/cve/CVE-2019-19588"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1158542 for CVE-2019-19588",
				"url": "https://bugzilla.suse.com/1158542"
			}
		],
		"title": "SUSE CVE CVE-2019-19588",
		"tracking": {
			"current_release_date": "2023-02-15T04:05:58Z",
			"generator": {
				"date": "2023-02-15T04:05:58Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2019-19588",
			"initial_release_date": "2023-02-15T04:05:58Z",
			"revision_history": [
				{
					"date": "2023-02-15T04:05:58Z",
					"number": "2",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "2"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python310-validators-0.24.0-1.2",
								"product": {
									"name": "python310-validators-0.24.0-1.2",
									"product_id": "python310-validators-0.24.0-1.2"
								}
							},
							{
								"category": "product_version",
								"name": "python311-validators-0.24.0-1.2",
								"product": {
									"name": "python311-validators-0.24.0-1.2",
									"product_id": "python311-validators-0.24.0-1.2"
								}
							},
							{
								"category": "product_version",
								"name": "python312-validators-0.24.0-1.2",
								"product": {
									"name": "python312-validators-0.24.0-1.2",
									"product_id": "python312-validators-0.24.0-1.2"
								}
							},
							{
								"category": "product_version",
								"name": "python36-validators-0.18.1-2.4",
								"product": {
									"name": "python36-validators-0.18.1-2.4",
									"product_id": "python36-validators-0.18.1-2.4"
								}
							},
							{
								"category": "product_version",
								"name": "python38-validators-0.18.1-2.4",
								"product": {
									"name": "python38-validators-0.18.1-2.4",
									"product_id": "python38-validators-0.18.1-2.4"
								}
							},
							{
								"category": "product_version",
								"name": "python39-validators-0.18.1-2.4",
								"product": {
									"name": "python39-validators-0.18.1-2.4",
									"product_id": "python39-validators-0.18.1-2.4"
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-validators-0.24.0-1.2 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-validators-0.24.0-1.2"
				},
				"product_reference": "python310-validators-0.24.0-1.2",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-validators-0.24.0-1.2 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-validators-0.24.0-1.2"
				},
				"product_reference": "python311-validators-0.24.0-1.2",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-validators-0.24.0-1.2 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-validators-0.24.0-1.2"
				},
				"product_reference": "python312-validators-0.24.0-1.2",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python36-validators-0.18.1-2.4 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python36-validators-0.18.1-2.4"
				},
				"product_reference": "python36-validators-0.18.1-2.4",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python38-validators-0.18.1-2.4 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python38-validators-0.18.1-2.4"
				},
				"product_reference": "python38-validators-0.18.1-2.4",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-validators-0.18.1-2.4 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-validators-0.18.1-2.4"
				},
				"product_reference": "python39-validators-0.18.1-2.4",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-19588",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-19588"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-19588",
					"url": "https://www.suse.com/security/cve/CVE-2019-19588"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1158542 for CVE-2019-19588",
					"url": "https://bugzilla.suse.com/1158542"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python310-validators-0.24.0-1.2",
						"openSUSE Tumbleweed:python311-validators-0.24.0-1.2",
						"openSUSE Tumbleweed:python312-validators-0.24.0-1.2",
						"openSUSE Tumbleweed:python36-validators-0.18.1-2.4",
						"openSUSE Tumbleweed:python38-validators-0.18.1-2.4",
						"openSUSE Tumbleweed:python39-validators-0.18.1-2.4"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python310-validators-0.24.0-1.2",
						"openSUSE Tumbleweed:python311-validators-0.24.0-1.2",
						"openSUSE Tumbleweed:python312-validators-0.24.0-1.2",
						"openSUSE Tumbleweed:python36-validators-0.18.1-2.4",
						"openSUSE Tumbleweed:python38-validators-0.18.1-2.4",
						"openSUSE Tumbleweed:python39-validators-0.18.1-2.4"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-12-05T10:55:50Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-19588"
		}
	]
}
