{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "low"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2016-9014",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2016-9014",
				"url": "https://www.suse.com/security/cve/CVE-2016-9014"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1008047 for CVE-2016-9014",
				"url": "https://bugzilla.suse.com/1008047"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2018:0973-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003895.html"
			},
			{
				"category": "external",
				"summary": "Advisory link for SUSE-SU-2018:1102-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html"
			}
		],
		"title": "SUSE CVE CVE-2016-9014",
		"tracking": {
			"current_release_date": "2023-12-08T04:31:30Z",
			"generator": {
				"date": "2023-02-15T04:56:26Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2016-9014",
			"initial_release_date": "2023-02-15T04:56:26Z",
			"revision_history": [
				{
					"date": "2023-02-15T04:56:26Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2023-12-08T04:31:30Z",
					"number": "3",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "3"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 6",
								"product": {
									"name": "SUSE OpenStack Cloud 6",
									"product_id": "SUSE OpenStack Cloud 6",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:6"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 7",
								"product": {
									"name": "SUSE OpenStack Cloud 7",
									"product_id": "SUSE OpenStack Cloud 7",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django-1.8.19-3.4.1",
								"product": {
									"name": "python-Django-1.8.19-3.4.1",
									"product_id": "python-Django-1.8.19-3.4.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.8.19:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python-Django-1.8.19-3.6.1",
								"product": {
									"name": "python-Django-1.8.19-3.6.1",
									"product_id": "python-Django-1.8.19-3.6.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:1.8.19:*:*:*:*:*:*:*"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.8.19-3.6.1 as component of SUSE OpenStack Cloud 6",
					"product_id": "SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1"
				},
				"product_reference": "python-Django-1.8.19-3.6.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 6"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.8.19-3.4.1 as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-Django-1.8.19-3.4.1"
				},
				"product_reference": "python-Django-1.8.19-3.4.1",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2016-9014",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2016-9014"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Django before 1.8.x before 1.8.16, 1.9.x before 1.9.11, and 1.10.x before 1.10.3, when settings.DEBUG is True, allow remote attackers to conduct DNS rebinding attacks by leveraging failure to validate the HTTP Host header against settings.ALLOWED_HOSTS.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2016-9014",
					"url": "https://www.suse.com/security/cve/CVE-2016-9014"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1008047 for CVE-2016-9014",
					"url": "https://bugzilla.suse.com/1008047"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2018:0973-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003895.html"
				},
				{
					"category": "external",
					"summary": "Advisory link for SUSE-SU-2018:1102-1",
					"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.4.1"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 8.1,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.4.1"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2016-11-01T17:28:39Z",
					"details": "low"
				}
			],
			"title": "CVE-2016-9014"
		}
	]
}
