{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2020-26244",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "Python oic is a Python OpenID Connect implementation. In Python oic before version 1.2.1, there are several related cryptographic issues affecting client implementations that use the library. The issues are: 1) The IdToken signature algorithm was not checked automatically, but only if the expected algorithm was passed in as a kwarg. 2) JWA `none` algorithm was allowed in all flows. 3) oic.consumer.Consumer.parse_authz returns an unverified IdToken. The verification of the token was left to the discretion of the implementator. 4) iat claim was not checked for sanity (i.e. it could be in the future). These issues are patched in version 1.2.1.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2020-26244",
				"url": "https://www.suse.com/security/cve/CVE-2020-26244"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			}
		],
		"title": "SUSE CVE CVE-2020-26244",
		"tracking": {
			"current_release_date": "2023-02-15T03:53:15Z",
			"generator": {
				"date": "2023-02-15T03:53:15Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2020-26244",
			"initial_release_date": "2023-02-15T03:53:15Z",
			"revision_history": [
				{
					"date": "2023-02-15T03:53:15Z",
					"number": "2",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "2"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python36-oic-1.2.1-1.2",
								"product": {
									"name": "python36-oic-1.2.1-1.2",
									"product_id": "python36-oic-1.2.1-1.2"
								}
							},
							{
								"category": "product_version",
								"name": "python38-oic-1.2.1-1.2",
								"product": {
									"name": "python38-oic-1.2.1-1.2",
									"product_id": "python38-oic-1.2.1-1.2"
								}
							},
							{
								"category": "product_version",
								"name": "python39-oic-1.2.1-1.2",
								"product": {
									"name": "python39-oic-1.2.1-1.2",
									"product_id": "python39-oic-1.2.1-1.2"
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python36-oic-1.2.1-1.2 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python36-oic-1.2.1-1.2"
				},
				"product_reference": "python36-oic-1.2.1-1.2",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python38-oic-1.2.1-1.2 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python38-oic-1.2.1-1.2"
				},
				"product_reference": "python38-oic-1.2.1-1.2",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-oic-1.2.1-1.2 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-oic-1.2.1-1.2"
				},
				"product_reference": "python39-oic-1.2.1-1.2",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2020-26244",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-26244"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Python oic is a Python OpenID Connect implementation. In Python oic before version 1.2.1, there are several related cryptographic issues affecting client implementations that use the library. The issues are: 1) The IdToken signature algorithm was not checked automatically, but only if the expected algorithm was passed in as a kwarg. 2) JWA `none` algorithm was allowed in all flows. 3) oic.consumer.Consumer.parse_authz returns an unverified IdToken. The verification of the token was left to the discretion of the implementator. 4) iat claim was not checked for sanity (i.e. it could be in the future). These issues are patched in version 1.2.1.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-26244",
					"url": "https://www.suse.com/security/cve/CVE-2020-26244"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Tumbleweed:python36-oic-1.2.1-1.2",
						"openSUSE Tumbleweed:python38-oic-1.2.1-1.2",
						"openSUSE Tumbleweed:python39-oic-1.2.1-1.2"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.8,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:N",
						"version": "3.1"
					},
					"products": [
						"openSUSE Tumbleweed:python36-oic-1.2.1-1.2",
						"openSUSE Tumbleweed:python38-oic-1.2.1-1.2",
						"openSUSE Tumbleweed:python39-oic-1.2.1-1.2"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2020-12-03T00:57:12Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2020-26244"
		}
	]
}
