{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_vex",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2025 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "SUSE CVE-2021-32052",
				"title": "Title"
			},
			{
				"category": "description",
				"text": "In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.",
				"title": "Description of the CVE"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "CVE-2021-32052",
				"url": "https://www.suse.com/security/cve/CVE-2021-32052"
			},
			{
				"category": "external",
				"summary": "SUSE Security Ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "external",
				"summary": "SUSE Bug 1185713 for CVE-2021-32052",
				"url": "https://bugzilla.suse.com/1185713"
			},
			{
				"category": "external",
				"summary": "Advisory link for openSUSE-SU-2023:0005-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/UHF5IZKTZ2T4T4QQYZMUFHW422X3WCU6/"
			}
		],
		"title": "SUSE CVE CVE-2021-32052",
		"tracking": {
			"current_release_date": "2025-01-01T04:27:29Z",
			"generator": {
				"date": "2023-02-15T03:41:12Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf-vex.pl",
					"version": "1"
				}
			},
			"id": "CVE-2021-32052",
			"initial_release_date": "2023-02-15T03:41:12Z",
			"revision_history": [
				{
					"date": "2023-02-15T03:41:12Z",
					"number": "2",
					"summary": "Current version"
				},
				{
					"date": "2024-07-20T03:36:21Z",
					"number": "3",
					"summary": "Current version"
				},
				{
					"date": "2025-01-01T04:27:29Z",
					"number": "4",
					"summary": "Current version"
				}
			],
			"status": "interim",
			"version": "4"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Package Hub 15 SP3",
								"product": {
									"name": "SUSE Package Hub 15 SP3",
									"product_id": "SUSE Package Hub 15 SP3"
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Leap 15.3",
								"product": {
									"name": "openSUSE Leap 15.3",
									"product_id": "openSUSE Leap 15.3",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:leap:15.3"
									}
								}
							},
							{
								"category": "product_name",
								"name": "openSUSE Tumbleweed",
								"product": {
									"name": "openSUSE Tumbleweed",
									"product_id": "openSUSE Tumbleweed",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:tumbleweed"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python3-Django-2.2.28-bp153.2.3.1",
								"product": {
									"name": "python3-Django-2.2.28-bp153.2.3.1",
									"product_id": "python3-Django-2.2.28-bp153.2.3.1"
								}
							},
							{
								"category": "product_version",
								"name": "python310-Django-4.2.11-2.1",
								"product": {
									"name": "python310-Django-4.2.11-2.1",
									"product_id": "python310-Django-4.2.11-2.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:4.2.11:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python310-Django4-4.2.14-1.1",
								"product": {
									"name": "python310-Django4-4.2.14-1.1",
									"product_id": "python310-Django4-4.2.14-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python311-Django-4.2.11-2.1",
								"product": {
									"name": "python311-Django-4.2.11-2.1",
									"product_id": "python311-Django-4.2.11-2.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:4.2.11:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python311-Django4-4.2.14-1.1",
								"product": {
									"name": "python311-Django4-4.2.14-1.1",
									"product_id": "python311-Django4-4.2.14-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python312-Django-4.2.11-2.1",
								"product": {
									"name": "python312-Django-4.2.11-2.1",
									"product_id": "python312-Django-4.2.11-2.1",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:4.2.11:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python312-Django4-4.2.14-1.1",
								"product": {
									"name": "python312-Django4-4.2.14-1.1",
									"product_id": "python312-Django4-4.2.14-1.1"
								}
							},
							{
								"category": "product_version",
								"name": "python36-Django-3.2.7-2.3",
								"product": {
									"name": "python36-Django-3.2.7-2.3",
									"product_id": "python36-Django-3.2.7-2.3"
								}
							},
							{
								"category": "product_version",
								"name": "python38-Django-3.2.7-2.3",
								"product": {
									"name": "python38-Django-3.2.7-2.3",
									"product_id": "python38-Django-3.2.7-2.3",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:3.2.7:*:*:*:*:*:*:*"
									}
								}
							},
							{
								"category": "product_version",
								"name": "python39-Django-3.2.7-2.3",
								"product": {
									"name": "python39-Django-3.2.7-2.3",
									"product_id": "python39-Django-3.2.7-2.3",
									"product_identification_helper": {
										"cpe": "cpe:2.3:a:djangoproject:django:3.2.7:*:*:*:*:*:*:*"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-Django-2.2.28-bp153.2.3.1 as component of SUSE Package Hub 15 SP3",
					"product_id": "SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1"
				},
				"product_reference": "python3-Django-2.2.28-bp153.2.3.1",
				"relates_to_product_reference": "SUSE Package Hub 15 SP3"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-Django-2.2.28-bp153.2.3.1 as component of openSUSE Leap 15.3",
					"product_id": "openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1"
				},
				"product_reference": "python3-Django-2.2.28-bp153.2.3.1",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-Django-4.2.11-2.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-Django-4.2.11-2.1"
				},
				"product_reference": "python310-Django-4.2.11-2.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python310-Django4-4.2.14-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python310-Django4-4.2.14-1.1"
				},
				"product_reference": "python310-Django4-4.2.14-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-Django-4.2.11-2.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-Django-4.2.11-2.1"
				},
				"product_reference": "python311-Django-4.2.11-2.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python311-Django4-4.2.14-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python311-Django4-4.2.14-1.1"
				},
				"product_reference": "python311-Django4-4.2.14-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-Django-4.2.11-2.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-Django-4.2.11-2.1"
				},
				"product_reference": "python312-Django-4.2.11-2.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python312-Django4-4.2.14-1.1 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python312-Django4-4.2.14-1.1"
				},
				"product_reference": "python312-Django4-4.2.14-1.1",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python36-Django-3.2.7-2.3 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python36-Django-3.2.7-2.3"
				},
				"product_reference": "python36-Django-3.2.7-2.3",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python38-Django-3.2.7-2.3 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python38-Django-3.2.7-2.3"
				},
				"product_reference": "python38-Django-3.2.7-2.3",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python39-Django-3.2.7-2.3 as component of openSUSE Tumbleweed",
					"product_id": "openSUSE Tumbleweed:python39-Django-3.2.7-2.3"
				},
				"product_reference": "python39-Django-3.2.7-2.3",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2021-32052",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-32052"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1",
					"openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1",
					"openSUSE Tumbleweed:python310-Django-4.2.11-2.1",
					"openSUSE Tumbleweed:python310-Django4-4.2.14-1.1",
					"openSUSE Tumbleweed:python311-Django-4.2.11-2.1",
					"openSUSE Tumbleweed:python311-Django4-4.2.14-1.1",
					"openSUSE Tumbleweed:python312-Django-4.2.11-2.1",
					"openSUSE Tumbleweed:python312-Django4-4.2.14-1.1",
					"openSUSE Tumbleweed:python36-Django-3.2.7-2.3",
					"openSUSE Tumbleweed:python38-Django-3.2.7-2.3",
					"openSUSE Tumbleweed:python39-Django-3.2.7-2.3"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-32052",
					"url": "https://www.suse.com/security/cve/CVE-2021-32052"
				},
				{
					"category": "external",
					"summary": "SUSE Security Ratings",
					"url": "https://www.suse.com/support/security/rating/"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185713 for CVE-2021-32052",
					"url": "https://bugzilla.suse.com/1185713"
				},
				{
					"category": "external",
					"summary": "Advisory link for openSUSE-SU-2023:0005-1",
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/UHF5IZKTZ2T4T4QQYZMUFHW422X3WCU6/"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Tumbleweed:python310-Django-4.2.11-2.1",
						"openSUSE Tumbleweed:python310-Django4-4.2.14-1.1",
						"openSUSE Tumbleweed:python311-Django-4.2.11-2.1",
						"openSUSE Tumbleweed:python311-Django4-4.2.14-1.1",
						"openSUSE Tumbleweed:python312-Django-4.2.11-2.1",
						"openSUSE Tumbleweed:python312-Django4-4.2.14-1.1",
						"openSUSE Tumbleweed:python36-Django-3.2.7-2.3",
						"openSUSE Tumbleweed:python38-Django-3.2.7-2.3",
						"openSUSE Tumbleweed:python39-Django-3.2.7-2.3"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"SUSE Package Hub 15 SP3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Leap 15.3:python3-Django-2.2.28-bp153.2.3.1",
						"openSUSE Tumbleweed:python310-Django-4.2.11-2.1",
						"openSUSE Tumbleweed:python310-Django4-4.2.14-1.1",
						"openSUSE Tumbleweed:python311-Django-4.2.11-2.1",
						"openSUSE Tumbleweed:python311-Django4-4.2.14-1.1",
						"openSUSE Tumbleweed:python312-Django-4.2.11-2.1",
						"openSUSE Tumbleweed:python312-Django4-4.2.14-1.1",
						"openSUSE Tumbleweed:python36-Django-3.2.7-2.3",
						"openSUSE Tumbleweed:python38-Django-3.2.7-2.3",
						"openSUSE Tumbleweed:python39-Django-3.2.7-2.3"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-05-06T09:18:58Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2021-32052"
		}
	]
}
